export const schema = [
  `CREATE TABLE IF NOT EXISTS installation(id INTEGER PRIMARY KEY CHECK(id=1),seeded INTEGER NOT NULL,salt_key TEXT NOT NULL)`,
  `CREATE TABLE IF NOT EXISTS settings(id INTEGER PRIMARY KEY CHECK(id=1),data TEXT NOT NULL,version INTEGER NOT NULL DEFAULT 1)`,
  `CREATE TABLE IF NOT EXISTS users(id TEXT PRIMARY KEY,username TEXT UNIQUE NOT NULL,name TEXT NOT NULL,role TEXT NOT NULL CHECK(role IN ('owner','cashier','kitchen')),salt TEXT NOT NULL,verifier TEXT NOT NULL,active INTEGER NOT NULL DEFAULT 1,version INTEGER NOT NULL DEFAULT 1)`,
  `CREATE TABLE IF NOT EXISTS sessions(token_hash TEXT PRIMARY KEY,user_id TEXT REFERENCES users(id),csrf TEXT NOT NULL,expires INTEGER NOT NULL)`,
  `CREATE INDEX IF NOT EXISTS sessions_expiry ON sessions(expires)`,
  `CREATE TABLE IF NOT EXISTS presence(user_id TEXT PRIMARY KEY REFERENCES users(id),seen INTEGER NOT NULL)`,
  `CREATE TABLE IF NOT EXISTS rates(bucket TEXT PRIMARY KEY,count INTEGER NOT NULL,expires INTEGER NOT NULL)`,
  `CREATE TABLE IF NOT EXISTS products(id TEXT PRIMARY KEY,name TEXT NOT NULL,price INTEGER NOT NULL CHECK(price>=0),single_price INTEGER CHECK(single_price IS NULL OR single_price>=0),description TEXT NOT NULL,kind TEXT NOT NULL,category TEXT NOT NULL,photo TEXT NOT NULL,photo_note TEXT NOT NULL,active INTEGER NOT NULL,version INTEGER NOT NULL DEFAULT 1,sort INTEGER NOT NULL)`,
  `CREATE TABLE IF NOT EXISTS inventory(day TEXT NOT NULL,product_id TEXT NOT NULL REFERENCES products(id),remaining INTEGER NOT NULL CHECK(remaining>=0),PRIMARY KEY(day,product_id))`,
  `CREATE TABLE IF NOT EXISTS orders(seq INTEGER PRIMARY KEY AUTOINCREMENT,id TEXT UNIQUE NOT NULL,key_hash TEXT UNIQUE NOT NULL,fingerprint TEXT NOT NULL,day TEXT NOT NULL,slot TEXT NOT NULL,pickup_at INTEGER NOT NULL,name TEXT NOT NULL,phone TEXT NOT NULL,note TEXT NOT NULL,items TEXT NOT NULL,resources TEXT NOT NULL,units INTEGER NOT NULL CHECK(units>0),total INTEGER NOT NULL CHECK(total>=0),discount INTEGER NOT NULL,own_boxes INTEGER NOT NULL,soup INTEGER NOT NULL,status TEXT NOT NULL CHECK(status IN ('pending','accepted','preparing','ready','completed','cancelled','rejected','no_show')),payment TEXT NOT NULL DEFAULT 'unpaid' CHECK(payment IN ('unpaid','paid','refunded')),created_at INTEGER NOT NULL,expires_at INTEGER NOT NULL,updated_at INTEGER NOT NULL,version INTEGER NOT NULL DEFAULT 1)`,
  `CREATE INDEX IF NOT EXISTS orders_queue ON orders(day,status,slot)`,
  `CREATE INDEX IF NOT EXISTS orders_phone ON orders(phone,status)`,
  `CREATE INDEX IF NOT EXISTS orders_expiry ON orders(status,expires_at)`,
  `CREATE TABLE IF NOT EXISTS payments(id INTEGER PRIMARY KEY AUTOINCREMENT,order_id TEXT NOT NULL REFERENCES orders(id),user_id TEXT NOT NULL REFERENCES users(id),kind TEXT NOT NULL CHECK(kind IN ('cash','refund')),amount INTEGER NOT NULL,created_at INTEGER NOT NULL,UNIQUE(order_id,kind))`,
  `CREATE TABLE IF NOT EXISTS events(id INTEGER PRIMARY KEY AUTOINCREMENT,order_id TEXT,user_id TEXT,action TEXT NOT NULL,detail TEXT NOT NULL,created_at INTEGER NOT NULL)`,
  `CREATE TABLE IF NOT EXISTS media(id TEXT PRIMARY KEY,mime TEXT NOT NULL,body BLOB NOT NULL,size INTEGER NOT NULL,created_at INTEGER NOT NULL)`,
  `CREATE TABLE IF NOT EXISTS tx_guards(pass INTEGER NOT NULL CHECK(pass=1))`,
  `CREATE TRIGGER IF NOT EXISTS reserve_stock AFTER INSERT ON orders BEGIN UPDATE inventory SET remaining=remaining-COALESCE((SELECT CAST(value AS INTEGER) FROM json_each(NEW.resources) WHERE key=inventory.product_id),0) WHERE day=NEW.day AND product_id IN (SELECT key FROM json_each(NEW.resources)); END`,
  `CREATE TRIGGER IF NOT EXISTS release_stock AFTER UPDATE OF status ON orders WHEN OLD.status IN ('pending','accepted') AND NEW.status IN ('cancelled','rejected','no_show') BEGIN UPDATE inventory SET remaining=remaining+COALESCE((SELECT CAST(value AS INTEGER) FROM json_each(OLD.resources) WHERE key=inventory.product_id),0) WHERE day=OLD.day AND product_id IN (SELECT key FROM json_each(OLD.resources)); END`,
  `CREATE INDEX IF NOT EXISTS orders_retention ON orders(updated_at)`,
  `CREATE INDEX IF NOT EXISTS rates_expiry ON rates(expires)`,
];
